import type { Metadata } from "next";
import "@/styles/index.css";
import { interFont, soraFont } from "@/config/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interFont.variable} ${soraFont.variable} font-inter`}>
        {children}
      </body>
    </html>
  );
}
